//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examsystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class exam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public exam()
        {
            this.Reports = new HashSet<Report>();
        }
    
        public string exam_id { get; set; }
        public string exam_description { get; set; }
        public string category_id { get; set; }
       
        public int levelid { get; set; }
        public Nullable<System.DateTime> duration { get; set; }
        public Nullable<int> Noofquestion { get; set; }
        public Nullable<int> marks { get; set; }
        public Nullable<int> totalmarks { get; set; }
        public Nullable<int> passmarks { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Reports { get; set; }
    }
}
