//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examsystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int Qid { get; set; }
        public string Q_text { get; set; }
        public string QA { get; set; }
        public string QB { get; set; }
        public string QC { get; set; }
        public string QD { get; set; }
        public string Qcorrectans { get; set; }
        public string category_id { get; set; }
        public Nullable<int> levelid { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
