//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examsystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int result_id { get; set; }
        public string result_status { get; set; }
        public Nullable<int> result_score { get; set; }
        public string user_id { get; set; }
        public string exam_id { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual exam exam { get; set; }
    }
}
